print("fahad imam")
print("here i am here to learn python")
print("this is me fahad imam")
print("i sam gonna learn python fro m code with harry")
print(2223/34)
print(78/3)
print("this is me fahad imam is a \"good\"\n boy")
print("the student of jamia hamdard\n btech cse interested in machiong learing ")
print("hey guys this is me here to learn \"something\" new")
print("here i am here to come from the new country ")
print("here is something neew \'hello\' thingd")
print("hello guys this is me mozammil form galgotia university")
print("here i ma here for learing do something new about he machine learing \n ok first ",909+45)
print("here guys this is me fahad imam from btech cse")
print("hello man let\'s\' know how to seperste about the ",7,7 ,sep="#")
print("hello world this is a fahad imam")
print("hello man this is me fahad imam")
print("hello man this is \"fahad\" from \n btech cse",7,8,sep="a")